spring:
  application:
    name: spring-cloud-service-admin
  zipkin:
    base-url: http://localhost:9411
server:
  port: 8772

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/